#k8s module variables
verify_cluster_ssl: 'no'

#CL and EO,
#TODO make these dynamic.

#oc get packagemanifest elasticsearch-operator -n openshift-marketplace -o jsonpath='{.status.channels[].name}'
channel: 'preview'

#oc get packagemanifest elasticsearch-operator -n openshift-marketplace -o jsonpath='{.status.channels[].currentCSV}'
csv: 'elasticsearch-operator.4.1.4-201906271212'

#oc get packagemanifest cluster-logging -n openshift-marketplace -o jsonpath='{.status.channels[].currentCSV}'
clv: 'clusterlogging.4.1.4-201906271212'

#Elasticsearch, fluentd, kibana variables
es_node_count: 1
#es_node_count: 3
es_disk_size: "200G"
es_storageclass: "gp2"
#Options: FullRedundancy, MultipleRedundancy,(SingleRedundancy),ZeroRedundancy
es_redundancy: "ZeroRedundancy"
es_cpu_limit: "1"
es_cpu_request: "1"
es_memory_limit: "4Gi"
es_memory_request: "4Gi"
es_instance_ram: "4Gi"
kibana_replicas: 1

#Ansible Paths
template_path : 'roles/efk-part1/templates/'
manifests_path: 'roles/efk-part1/generated-manifests'
